apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-app
  namespace: rails-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rails-app
  template:
    metadata:
      labels:
        app: rails-app
    spec:
      containers:
      - name: rails-app
        image: docker.io/aryanrawwat/budget-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_HOST
          value: postgres
        - name: DATABASE_NAME
          value: railsdb
        - name: DATABASE_USER
          value: railsuser
        - name: DATABASE_PASSWORD
          value: railspassword

