default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: railsuser
  password: railspassword
  host: postgres
  port: 5432

development:
  <<: *default
  database: railsdb

test:
  <<: *default
  database: railsdb_test

production:
  <<: *default
  database: railsdb

